#YouTube Tech Channels Statistics 2025

In [1]:
#link to the Kaggle dataset -> https://www.kaggle.com/datasets/mihikaajayjadhav/youtube-tech-channels-statistics-2025?select=youtube_tech_channels_20251120_133753.csv

import pandas as pd
import numpy as np

##Data Exploration

In [2]:
df_yt_tech_channels = pd.read_csv("/content/youtube_tech_channels.csv")

df_yt_tech_vids = pd.read_csv("/content/youtube_tech_videos.csv")

In [4]:
df_yt_tech_channels.info()

df_yt_tech_vids.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   channel_id        130 non-null    object
 1   channel_name      130 non-null    object
 2   description       127 non-null    object
 3   subscribers       130 non-null    int64
 4   total_views       130 non-null    int64
 5   total_videos      130 non-null    int64
 6   created_date      130 non-null    object
 7   country           116 non-null    object
 8   uploads_playlist  130 non-null    object
 9   scraped_at        130 non-null    object
dtypes: int64(3), object(7)
memory usage: 10.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           1300 non-null   object
 1   title              1300 non-null   object
 2   published_at       1300 non-null   object
 3   views              1300 non-null   int64
 4   likes              1300 non-null   int64
 5   comments           1300 non-null   int64
 6   duration           1300 non-null   object
 7   thumbnail          1300 non-null   object
 8   video_url          1300 non-null   object
 9   channel_id         1300 non-null   object
 10  channel_name       1300 non-null   object
 11  scraped_at         1300 non-null   object
 12  duration_readable  1300 non-null   object
dtypes: int64(3), object(10)
memory usage: 132.2+ KB

In [5]:
'''
------------------------------------
Column Descriptions (source: Kaggle)
------------------------------------
Channels:
channel_id: Unique YouTube channel identifier
channel_name: Display name of the channel
description: Channel description (first 500 chars)
subscribers: Number of subscribers
total_views: Lifetime view count
total_videos: Total videos published
created_date: Channel creation date
country: Channel's country (if available)
scraped_at: Data collection timestamp

Videos:
video_id: Unique YouTube video identifier
title: Video title
published_at: Upload timestamp
views: View count
likes: Like count
comments: Comment count
duration: Video duration (ISO 8601 format)
thumbnail: High-quality thumbnail URL
video_url: Direct link to video
channel_id: Parent channel ID
channel_name: Parent channel name
scraped_at: Data collection timestamp
'''

"\n------------------------------------\nColumn Descriptions (source: Kaggle)\n------------------------------------\nChannels:\nchannel_id: Unique YouTube channel identifier\nchannel_name: Display name of the channel\ndescription: Channel description (first 500 chars)\nsubscribers: Number of subscribers\ntotal_views: Lifetime view count\ntotal_videos: Total videos published\ncreated_date: Channel creation date\ncountry: Channel's country (if available)\nscraped_at: Data collection timestamp\n\nVideos:\nvideo_id: Unique YouTube video identifier\ntitle: Video title\npublished_at: Upload timestamp\nviews: View count\nlikes: Like count\ncomments: Comment count\nduration: Video duration (ISO 8601 format)\nthumbnail: High-quality thumbnail URL\nvideo_url: Direct link to video\nchannel_id: Parent channel ID\nchannel_name: Parent channel name\nscraped_at: Data collection timestamp\n"

In [7]:
df_yt_tech_channels.describe(include='all')

,channel_id,channel_name,description,subscribers,total_views,total_videos,created_date,country,uploads_playlist,scraped_at
count,130,130,127,1.300000e+02,1.300000e+02,130.000000,130,116,130,130
unique,130,130,127,NaN,NaN,NaN,130,24,130,1
top,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,"Linus Tech Tips is a passionate team of ""profe...",NaN,NaN,NaN,2008-11-25T00:46:52Z,US,UUXuqSBlHAE6Xw-yeJA0Tunw,2025-11-20T13:37:53.306286
freq,1,1,1,NaN,NaN,NaN,1,54,1,130
mean,NaN,NaN,NaN,5.123438e+05,1.237155e+08,963.769231,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,1.588629e+06,8.068909e+08,2279.711639,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,1.080000e+04,2.678500e+04,13.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,3.700000e+04,2.681172e+06,191.250000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,1.200000e+05,1.059262e+07,374.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,4.120000e+05,3.823083e+07,831.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,1.660000e+07,9.092244e+09,18375.000000,NaN,NaN,NaN,NaN

In [8]:
df_yt_tech_vids.describe(include='all')

,video_id,title,published_at,views,likes,comments,duration,thumbnail,video_url,channel_id,channel_name,scraped_at,duration_readable
count,1300,1300,1300,1.300000e+03,1300.000000,1300.000000,1300,1300,1300,1300,1300,1300,1300
unique,1300,1288,1300,NaN,NaN,NaN,974,1300,1300,130,130,1,974
top,bHEmp5YIUI4,Sheryians AI Live QnA session,2023-08-18T19:01:05Z,NaN,NaN,NaN,PT1M,https://i.ytimg.com/vi/bHEmp5YIUI4/hqdefault.jpg,https://www.youtube.com/watch?v=bHEmp5YIUI4,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,2025-11-20T13:37:53.306773,1:00
freq,1,3,1,NaN,NaN,NaN,11,1,1,10,10,1300,11
mean,NaN,NaN,NaN,1.394824e+05,2868.888462,133.875385,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,2.299066e+06,20527.502375,757.578859,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000e+00,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,8.532500e+02,24.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,3.327500e+03,104.000000,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,1.814900e+04,624.500000,49.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,7.960118e+07,477913.000000,16969.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
columns_yt_tech_channels = [
    'channel_id', 'channel_name', 'description', 'subscribers',
    'total_views', 'total_videos', 'created_date', 'country',
    'scraped_at'
]

for col in columns_yt_tech_channels:
    missing = df_yt_tech_channels[col].isna().sum()
    duplicated = df_yt_tech_channels[col].duplicated().sum()
    total_non_null = df_yt_tech_channels[col].count()

    print(f"--- {col} ---")
    print(f"Missing values:        {missing}")
    print(f"Duplicated values:     {duplicated}")
    print(f"Total non-null values: {total_non_null}\n")

--- channel_id ---
Missing values:        0
Duplicated values:     0
Total non-null values: 130

--- channel_name ---
Missing values:        0
Duplicated values:     0
Total non-null values: 130

--- description ---
Missing values:        3
Duplicated values:     2
Total non-null values: 127

--- subscribers ---
Missing values:        0
Duplicated values:     8
Total non-null values: 130

--- total_views ---
Missing values:        0
Duplicated values:     0
Total non-null values: 130

--- total_videos ---
Missing values:        0
Duplicated values:     10
Total non-null values: 130

--- created_date ---
Missing values:        0
Duplicated values:     0
Total non-null values: 130

--- country ---
Missing values:        14
Duplicated values:     105
Total non-null values: 116

--- scraped_at ---
Missing values:        0
Duplicated values:     129
Total non-null values: 130

In [10]:
columns_yt_tech_vids = [
    'video_id', 'title', 'published_at', 'views', 'likes', 'comments',
    'duration', 'thumbnail', 'video_url', 'channel_id',
    'channel_name', 'scraped_at'
]

for col in columns_yt_tech_vids:
    missing = df_yt_tech_vids[col].isna().sum()
    duplicated = df_yt_tech_vids[col].duplicated().sum()
    total_non_null = df_yt_tech_vids[col].count()

    print(f"--- {col} ---")
    print(f"Missing values:        {missing}")
    print(f"Duplicated values:     {duplicated}")
    print(f"Total non-null values: {total_non_null}\n")

--- video_id ---
Missing values:        0
Duplicated values:     0
Total non-null values: 1300

--- title ---
Missing values:        0
Duplicated values:     12
Total non-null values: 1300

--- published_at ---
Missing values:        0
Duplicated values:     0
Total non-null values: 1300

--- views ---
Missing values:        0
Duplicated values:     92
Total non-null values: 1300

--- likes ---
Missing values:        0
Duplicated values:     668
Total non-null values: 1300

--- comments ---
Missing values:        0
Duplicated values:     1029
Total non-null values: 1300

--- duration ---
Missing values:        0
Duplicated values:     326
Total non-null values: 1300

--- thumbnail ---
Missing values:        0
Duplicated values:     0
Total non-null values: 1300

--- video_url ---
Missing values:        0
Duplicated values:     0
Total non-null values: 1300

--- channel_id ---
Missing values:        0
Duplicated values:     1170
Total non-null values: 1300

--- channel_name ---
Missing values:        0
Duplicated values:     1170
Total non-null values: 1300

--- scraped_at ---
Missing values:        0
Duplicated values:     1299
Total non-null values: 1300